### ISSUE TITLE
Error when trying to use the --keyid parameter: keyid is not defined

### ISSUE THREAD

**Issue by Jimbobnz** [mattroberts297/jsonwebtokencli#2]
ReferenceError: keyid is not defined
    at module.exports (C:\Users\James\AppData\Roaming\npm\node_modules\jsonwebtokencli\convert.js:35:24)
    at getStdin.then.stdin (C:\Users\James\AppData\Roaming\npm\node_modules\jsonwebtokencli\main.js:43:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

version: jsonwebtokencli v1.3.0

**Comment by mattroberts297** [comment]
This should be fixed in 1.5.1 - please reopen if not.
